version: "3.8"
services:
  postgres-db:
    container_name: postgres_fullstack_phase2
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_dev
    ports:
      - "5432:5432"
  postgres-test-db:
    container_name: postgres-test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_test_dev
    ports:
      - "5433:5432"